apiVersion: v2
description: A Helm chart to deploy Linkerd CRDs to Kubernetes
maintainers:
- email: devops@indico.io
  name: indico-devops
  url: https://indicodata.ai
name: linkerd-crds
type: application
version: 0.3.0-IPA-7.5.4
