apiVersion: v2
description: A Helm chart to deploy Trust Manager to Kubernetes
maintainers:
- email: devops@indico.io
  name: indico-devops
  url: https://indicodata.ai
name: trust-manager
type: application
version: 0.3.2-IPA-7.8.1
