apiVersion: v2
description: A Helm chart to deploy Linkerd multicluster to Kubernetes
maintainers:
- email: devops@indico.io
  name: indico-devops
  url: https://indicodata.ai
name: linkerd-multicluster
type: application
version: 0.7.2-IPA-7.8.0
