apiVersion: v2
description: A Helm chart to deploy Linkerd viz to Kubernetes
maintainers:
- email: devops@indico.io
  name: indico-devops
  url: https://indicodata.ai
name: linkerd-viz
type: application
version: 0.7.2-IPA-7.8.3
